### ISSUE TITLE
todos

### ISSUE THREAD

**Issue by ronnyle** [tuffk/loomRelayDocker#1]
- please fix the Alpine version
- please remove the `SEND_IP` related configuration which you don't use anyway
- why do you need to do all the `touch` stuff
- try and remove all unneeded dependencies as long as it still works (e.g. gnutls)
- remove the self-signed certificate (I don't think it's required)
- add the option to run the container with a `DEBUG` environment variable, in which case the rsyslog with start with `-D` flag
- fail if no `CUSTOMER_NAME` is given
- test!

**Comment by tuffk** [comment]
1. alpine version fixed
2. removed `SEND_IP`
3. removed the `touch` for the files that were being used for debug
4. removed all unnecessary packages and remove those that are used only once after use
5. removed the certificate
6. added an `if ... else.. ` to `config.sh` to work with an ENV variable

**Comment by tuffk** [comment]
1. added an `if ` that exits the container when no CUTOMER_NAME is specified
